# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=10)),
                ('upwd', models.CharField(max_length=40)),
                ('ushouji', models.CharField(default='', max_length=15)),
                ('uyoubian', models.CharField(default='', max_length=8)),
                ('uemail', models.CharField(max_length=40)),
                ('uaddress', models.CharField(max_length=40)),
            ],
        ),
    ]
